### ISSUE TITLE
Empty RPU

### ISSUE THREAD

**Issue by darkjumpy** [jlw4049/HDR-Multi-Tool-Gui#12]
Hi, I have a problem with your app. I'm unable to extract any RPU from DoVi. I always get an empty bin file whatever my settings are. The Dolby profile of my files is 07.06

**Comment by jessielw** [comment]
Do you think you could possibly give me a small sample of this file? A couple minutes of it, you can split it up with MKVToolNix and send me the sample so I can test it here locally and figure out what's going on. 

I did some tests on some files I had here for both HDR10Plus and Dolby Vision and both of them worked properly.

**Comment by darkjumpy** [comment]
[Here is 15min of my file](https://drive.google.com/file/d/1g05FsBz075tDvL86T832odjrICwl6ElZ/view?usp=sharing)

**Comment by cartman0208** [comment]
Had the same issue, but the logfile gave me a hint

`FFMPEG 2024-01-24T12:40:49.795Z: Unrecognized option 'vbsf'.`

It seems the wrong ffmpeg.exe is called, in my case there was an environment variable set to a folder where a newer version of ffmpeg was located, which obviously did not feature the vbsf option anymore.
Guess that can be solved by calling the ffmpeg.exe in the /apps folder of HDR-Multi-Tool explicitly

My workaround was to add another environment variable pointing to the /apps folder and locating it above the other variable giving it a higher priority.
Then the extraction worked again.

**Comment by jessielw** [comment]
I'll take a look at both of these issues today, although these are potentially separate issues.

**Comment by jessielw** [comment]
> [Here is 15min of my file](https://drive.google.com/file/d/1g05FsBz075tDvL86T832odjrICwl6ElZ/view?usp=sharing)

Your source file has invalid/incorrect dolby vision metadata. It cannot be parsed. 

```
Error: No NALU start codes found in the file. Maybe not a valid RPU?
```

Unfortunately there isn't much I can do about the invalid metadata. This is generally due to improper injection of the metadata in the source. However, in the latest release I added a check that will alert the user if invalid metadata was detected post extraction. 

https://github.com/jlw4049/HDR-Multi-Tool/releases/tag/2.0.1
