### ISSUE TITLE
HDR Multi Tool with Dolby Vision and Movies Modest

### ISSUE THREAD

**Issue by Ragnaroeko** [jlw4049/HDR-Multi-Tool-Gui#17]
Suggestion or extension if possible!?

Foreword:
I use Staxrip and HDR Multi Tool (only for a short time), after working with Staxrip for over a year I can at least get by with it to the point where I get good results. Despite the documentation, I don't have more detailed information on some options to gain more knowledge about them.

Process and example for a 1920x1080p video:
I often use the Crop function and cut away the black stripes in a film. I also cut away a bit to the left and right of the image, about 100 on the left and 100 on the right. This makes the video image a bit larger without losing much quality. In addition, most scenes take place more in the middle of the image, so that 98% of the time nothing important is lost through cropping in most videos. After that I use Resize to 1920x1080p. Without Dolby Vision, this works really well with Staxrip.

Example for a 1920x1080p video/film:
Left -100, right -100, remove black stripes/bars at the top and bottom.

Problem and suggestion for an extension for HDR Multi Tool:
After cutting, I can no longer use the Dolby Vision (HDR10+) resize function for films to set them back to 1080p (1920x1080p). I have the same problem with 4K video (3840x2160p). It doesn't really work because of the Dolby Vision! There is also often a problem when I want to convert from 4K video to Full HD, especially if I crop the video beforehand as described. I have also used HDR Multi Tool Crop, but unfortunately I can't set it to 1080p with Resize.

Is there a way for your program to not only offer cropping, but also zooming to 1920x1080? My English isn't that good, sorry! I hope you understand me and what I mean!? For example, I crop a 1920x1080p video, which then has 1720x816. Now I want to zoom it back up to 1920x1080p so that the video is compatible with some players and devices. Unfortunately, this is not possible with your HDR Multi Tool program. Of course, Staxrip does not work either unless I remove Dolby Vision, which I don't really want to do. Unfortunately, I don't have a TV with Dolby Vision yet to be able to check this, my Sony only has HDR10 and HLG. If I buy a new TV with HDR10+ and Dolby Vision at some point, I don't want to be surprised that the colors in the video are no longer correct. I could imagine that this could happen if I mess up the video material now, or do something wrong.

Best wishes from Germany

**Comment by jessielw** [comment]
Hello,

> Process and example for a 1920x1080p video:
> I often use the Crop function and cut away the black stripes in a film. I also cut away a bit to the left and right of the image, about 100 on the left and 100 on the right. This makes the video image a bit larger without losing much quality. In addition, most scenes take place more in the middle of the image, so that 98% of the time nothing important is lost through cropping in most videos. After that I use Resize to 1920x1080p. Without Dolby Vision, this works really well with Staxrip.
> 
> Example for a 1920x1080p video/film:
> Left -100, right -100, remove black stripes/bars at the top and bottom.

I wouldn't crop the left and ride sides of the film if there is video. You generally only ever want to crop black bars off of videos, especially when dealing with any HDR metadata. I would leave the sides alone and use a resize filter to drop the video down to `1920x1080p`. In StaxRip you could just use the `Auto x 1080p` and it'll handle all the calculations for you. 

> Problem and suggestion for an extension for HDR Multi Tool:
> After cutting, I can no longer use the Dolby Vision (HDR10+) resize function for films to set them back to 1080p (1920x1080p). I have the same problem with 4K video (3840x2160p). It doesn't really work because of the Dolby Vision! There is also often a problem when I want to convert from 4K video to Full HD, especially if I crop the video beforehand as described. I have also used HDR Multi Tool Crop, but unfortunately I can't set it to 1080p with Resize.
> 
> Is there a way for your program to not only offer cropping, but also zooming to 1920x1080? My English isn't that good, sorry! I hope you understand me and what I mean!? For example, I crop a 1920x1080p video, which then has 1720x816. Now I want to zoom it back up to 1920x1080p so that the video is compatible with some players and devices. Unfortunately, this is not possible with your HDR Multi Tool program. Of course, Staxrip does not work either unless I remove Dolby Vision, which I don't really want to do. Unfortunately, I don't have a TV with Dolby Vision yet to be able to check this, my Sony only has HDR10 and HLG. If I buy a new TV with HDR10+ and Dolby Vision at some point, I don't want to be surprised that the colors in the video are no longer correct. I could imagine that this could happen if I mess up the video material now, or do something wrong.

I think you are getting a couple terminologies mixed up. When you crop a video, it does nothing to the HDR metadata (dv) was designed for the original resolution. So if you crop the video at all you have to adjust the offsets to match. When it comes to 1080p. However, the latest release of this software would be capable to set those offsets properly. 

`HDR10+` will just work. 
`Dolby Vision` needs the offsets adjusted. You should only need to apply the `cropped` offsets, but the resize has nothing to do with this.
