### ISSUE TITLE
Importing new file (mkv) doesn't reset INFO

### ISSUE THREAD

**Issue by Rumourd** [jlw4049/HDR-Multi-Tool-Gui#3]
Open an MKV containing DV, it displays correct DV info. 
Open or drag in a new file without DV, the INFO AREA still displays old file's DV info.

**Comment by jessielw** [comment]
Thanks for the bug report, I'll get this fixed as soon as possible!

**Comment by Rumourd** [comment]
cool, i hope i hear about it!

**Comment by jessielw** [comment]
Latest release fixes what you needed

https://github.com/jlw4049/HDR-Multi-Tool-Gui/releases/tag/1.35
