### ISSUE TITLE
Constantly requires choosing folder 

### ISSUE THREAD

**Issue by noblemd00** [jlw4049/HDR-Multi-Tool-Gui#8]
Thanks, easy to use. One request - Is there a way to have the GUI retain the previous chosen folder when "Open File" - Constantly have to re-choose the same folder every time - maybe RootFolder = Selected Folder and the value will be retained until the GUI is closed.

**Comment by jessielw** [comment]
Yes, I'll try to take a look at this tomorrow and potentially get this done
